library(frasam)
# load_all()
context("data check")
test_that("test data",{
  data("dat_example",package="frasam")
  # dat = get(load(system.file("data","dat_example.rda",package="frasam")))
  caa <- read.csv(system.file("extdata","caa1_2023.csv",package="frasam"),row.names=1)
  waa <- read.csv(system.file("extdata","waa1_2023.csv",package="frasam"),row.names=1)
  maa <- read.csv(system.file("extdata","maa1_2023.csv",package="frasam"),row.names=1)
  cpue <- read.csv(system.file("extdata","cpue1_2023.csv",package="frasam"),row.names=1)
  dat_orig <- frasyr::data.handler(caa=caa, waa=waa, maa=maa, M=0.4,index=cpue)

  expect_equal(dim(dat$caa),dim(dat_orig$caa))

  # expect_equal(round(sum(abs(dat$caa-dat_orig$caa)),2),0)
  # expect_equal(round(sum(abs(dat$waa-dat_orig$waa)),2),0)
  # expect_equal(round(sum(abs(dat$maa-dat_orig$maa)),2),0)
  # expect_equal(round(sum(abs(dat$M-dat_orig$M)),2),0)
  # expect_equal(round(sum(abs(dat$index-dat_orig$index),na.rm = TRUE),2),0)

  # expect_equal(round(sum(abs(dat$caa-caa)),2),0)
  # expect_equal(round(sum(abs(dat$waa-waa)),2),0)
  # expect_equal(round(sum(abs(dat$maa-maa)),2),0)
  # expect_equal(round(sum(abs(dat$M-M)),2),0)
  # expect_equal(round(sum(abs(dat$index-index),na.rm = TRUE),2),0)
})
