---
title: "SAMを使った資源量推定"
author: "市野川桃子・西嶋翔太"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
    
vignette: >
  %\VignetteIndexEntry{1. Estimating abundances with SAM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# SAMのインストール
- インストールに必要なパッケージ(devtools)はあらかじめインストールしておいてください

```{r, fig.show='hold'}

# インストール
devtools::install_github("ichimomo/frasam@create_vignette") # frasamのインストール
devtools::install_github("ichimomo/frasyr@dev") # frasyrも使うのでfrasyrもインストールしてください

# ライブラリの呼び出し
library(frasyr)
library(frasam)
library(tidyverse)
library(patchwork)

```

# SAMを適用するデータセットの作成

VPAを適用するときのデータセットと同じ形式のデータセットが利用できます。
ただし、VPAでは資源量指数が利用できなくても適用できますが、SAMでは資源量指数の利用が必須になります。

## データの読み込み
```{r, fig.show='hold'}

caa   <- read.csv("https://raw.githubusercontent.com/ichimomo/frasyr/dev/data-raw/ex1_caa.csv",  row.names=1)
waa   <- read.csv("https://raw.githubusercontent.com/ichimomo/frasyr/dev/data-raw/ex1_waa.csv",  row.names=1)
maa   <- read.csv("https://raw.githubusercontent.com/ichimomo/frasyr/dev/data-raw/ex1_maa.csv",  row.names=1)
index <- read.csv("https://raw.githubusercontent.com/ichimomo/frasyr/dev/data-raw/ex1_index.csv",  row.names=1)
# create pseudo data for caa
caa   <- caa * exp(rnorm(length(caa), mean=-0.5 * (0.1)^2, sd=0.1))
dat <- data.handler(caa=caa, waa=waa, maa=maa, M=0.5, index=index)

# まずはsamのhelpファイルを閲覧してどんなオプションがあるか把握しましょう
#help(sam)

# これ必要？ tmb.run=TRUEだとsam2がないと言われた
use_sam_tmb(TmbFile="sam2",overwrite=FALSE) #compile and activate

# samの実施
# (*)の部分が設定ポイント
res_sam <- sam(dat,
        last.catch.zero = FALSE,
       	cpp.file.name = "sam2",
    	tmb.run = FALSE, # TRUEにするとtmbをコンパイルしてロードする。最初の１回だけTRUEにするのが良い
       	rec.age = 0,
       	plus.group = TRUE,
       	alpha = 1, # 最高年齢と最高年齢-1歳のFが同じと仮定
        est.method = "ml",	
	# 資源量指数に関わる設定。資源量指数の数だけベクトルで与える。
	abund = c("SSB"), 
       	min.age = c(0), 
       	max.age = c(6), 
       	b.est = FALSE, # b推定の有無(*)
       	b.fix = NA,
	# 分散に関わる設定。どの分散を同じとするか。年齢の数だけ与える (*)
	varC =  c(0,0,0,0,0,0,0),
        varN = c(0,1,1,1,1,1,1),
        varF = c(0,0,0,0,0,0,0),
        varN.fix = c(NA, 1e-4, 1e-4, 1e-4, 1e-4, 1e-4, 1e-4),
	# 再生産関係推定に関わる設定 (*)
	SR = "BH",
    AR = 0,
    # Fの多変量Random walkの非対角成分の相関係数のタイプ。１ならすべての年齢間で相関係数1, 0なら完全にランダム, 2は任意の年齢間で共通のrhoを推定、3は年齢i,jの相関を\eqn{\rho^|i-j|}で推定 (*)
    rho.mode = 0,
	# 初期値の設定
        q.init = NULL,
	sdFsta.init = NULL,
	sdLogN.init = c(0.2, 0.2),
        sdLogObs.init = NULL,
        rho.init = NULL,
        a.init = NULL,
        b.init = NULL,
	# その他
        ref.year = 1:5,
        bias.correct = TRUE,
        bias.correct.sd = FALSE,
        get.random.vcov = FALSE,
        silent = TRUE,
       remove.Fprocess.year = NULL,
       RW.Forder = 0,
       map.add = NULL,
       p0.list = NULL,
       scale = 1000,
       scale_number = 1000,       
       gamma = 10,
       sel.def = "max",
       use.index = NULL,
       upper = NULL,
       lower = NULL,
       index.key = NULL,
       index.b.key = NULL,
       lambda = 0,
       add_random = NULL,
       tmbdata = NULL,
       map = NULL,
       sep_omicron = TRUE,
       catch_prop = NULL,
       no_est = FALSE,
       getJointPrecision = FALSE,
       loopnum = 2
    )

# 推定結果の確認: opt=推定パラメータや目的関数、収束の有無 
res_sam$opt
# 推定結果の確認: rep=推定パラメータとSD
res_sam$rep
# 推定結果の確認: AIC
res_sam$aic
# 推定結果の確認: sigma
res_sam[c("sigma","sigma.logC","sigma.logFsta","sigma.logN")]

# 設定を変えてもう一度
sam_input <- res_sam$input
sam_input$rho.mode <- 1 # fix selectivity
res_sam2 <- do.call(sam, sam_input)

# AICの比較
c(res_sam$aic, res_sam2$aic)

# VPAもやってみる
res_vpa <- vpa(dat,fc.year=1998:2000,tf.year = 1998:1999,
               term.F="max",stat.tf="mean",Pope=TRUE,tune=TRUE,p.init=0.5, abund="SSB", min.age=0, max.age=6, sel.update=TRUE)

# ３つのモデルの比較
plot_vpa(list(VPA=res_vpa, SAM=res_sam, SAM2=res_sam2))

# SAMだけの比較 (fishing_mortalityはFの平均？)
plot_samvpa(list(SAM=res_sam, SAM2=res_sam2),what.plot = c("biomass","SSB","Recruitment","U","catch","fishing_mortality"))

# 結果の出力
res_samdata <- make_assess_result(res_sam)

# F at age by year
(gg <- res_samdata %>% dplyr::filter(stat=="faa") %>%
  ggplot() +
  geom_ribbon(aes(x=Age, ymax=upper, ymin=lower, group=Model, fill=Model), alpha=0.5) +
  geom_line(aes(x=Age, y=Value, colour=Model, group=Model, size=Model), linetype=1) +
  facet_wrap(.~Year, scales = "free_y", nrow=10, ncol=2, dir="v") +
  scale_y_continuous(limits = c(0, NA)) +
  scale_fill_manual("Model", values = c("#F8766D", "black")) +
  scale_colour_manual("Model", values = c("#F8766D", "black")) +
  scale_size_manual("Model", values = c(1, 0.5), guide = "none") +
  theme_bw() + labs(title="FAA", x=xlab, y=ylab) +
  theme(axis.text.x = element_text(size = 11, color = "black"), 
        axis.text.y = element_text(size = 11, color = "black"), 
        axis.line.x = element_line(linewidth = 0.3528), axis.line.y = element_line(linewidth = 0.3528), 
        axis.minor.ticks.length = rel(0.5)))

# F at age by year
(gg <- res_samdata %>% dplyr::filter(stat=="faa") %>%
   mutate(Age=factor(Age)) %>%
  ggplot() +
  geom_ribbon(aes(x=Year, ymax=upper, ymin=lower, group=Model, fill=Model), alpha=0.5) +
  geom_line(aes(x=Year, y=Value, colour=Model, group=Model), linetype=1) +
  facet_wrap(.~Age, scales = "free_y", nrow=10, ncol=2, dir="v") +
  scale_y_continuous(limits = c(0, NA)) +
#  scale_fill_manual("Model", values = c("#F8766D", "black")) +
#  scale_colour_manual("Model", values = c("#F8766D", "black")) +
#  scale_size_manual("Model", values = c(1, 0.5), guide = "none") +
  theme_bw() + labs(title="FAA", x=xlab, y=ylab) +
  theme(axis.text.x = element_text(size = 11, color = "black"), 
        axis.text.y = element_text(size = 11, color = "black"), 
        axis.line.x = element_line(linewidth = 0.3528), axis.line.y = element_line(linewidth = 0.3528), 
        axis.minor.ticks.length = rel(0.5)))


```

# モデル選択

```{r}
# 動かない
select_varN = select_sigma(res_sam, var="varN",X=2:6, stopAIC=TRUE)
select_varN$tbl_sigma
select_varN$reslist[[1]]$sigma
```

# 再生産関係のプロット

```{r}
SR_sam0 <- res_sam %>% make_SRres
plot_SR_simple(res_sam)
biopar <- derive_biopar(res_sam, derive_year=1998:2000)
steepness_sam <- calc_steepness(SR="BH", rec_pars=SR_sam0$pars,M=biopar$M, waa=biopar$waa, maa=biopar$maa)

```


# モデル診断

## 残差プロット

```{r}
# 資源量指数 (frasyrのplot_residual_vpaと統合してもよい？）
resid_sam <- index_plot(res_sam); wrap_plots(resid_sam)

# catch at age
caa_resid <- caa_plot(res_sam); wrap_plots(caa_resid)

# catch at age (sakai ver.)

caa_obs0 <- caa_obs %>% rownames_to_column(var="Age") %>% pivot_longer(cols=-Age, names_to="Year", values_to="Value") %>% mutate(Data="Observation")
caa_est0 <- res_sam$caa %>% as.data.frame %>% rownames_to_column(var="Age") %>% pivot_longer(cols=-Age, names_to="Year", values_to="Value") %>% mutate(Data="Estimation")
caa_obs_est <- bind_rows(caa_obs0, caa_est0)

xlab <- "年齢"
ylab <- "漁獲尾数（百万尾）"
scale <- 1000
g1 <- ggplot() +
  geom_bar(data=caa_obs0, stat="identity", aes(x=Age, y=Value/scale), col="black", fill="#FFFFB3") +
  geom_line(data=caa_est0, aes(x=Age, y=Value/scale, group=Data), col="#F8766D", linewidth=1.5) +
  facet_wrap(~Year, scales = "free_y", nrow=10, dir="v") +
  ylim(c(0, NA)) + scale_x_discrete(limit = c("0", "1", "2", "3", "4", "5", "6", "7", "8+")) +
  theme_bw() + labs(title="CAAプロット(棒グラフ：観測値, 折れ線：推定値)", x=xlab, y=ylab) +
  theme(axis.text.x = element_text(size = 11, color = "black"), 
        axis.text.y = element_text(size = 11, color = "black"), 
        axis.line.x = element_line(linewidth = 0.3528), axis.line.y = element_line(linewidth = 0.3528), 
        axis.minor.ticks.length = rel(0.5), legend.position = "none")


```

### レトロスペクティブ解析

```{r}
retro_sam(res_sam,n=1) ## tmbがクラッシュする
```

### プロファイル尤度
```{r}
res_profile <- samprofile(res_sam, "logQ", param_range=c(8, 11)) 
res_profile$obj_tbl %>% ggplot() + geom_line(aes(x=par, y=obj_value)) # 図示のための関数はある？

# Mのプロファイル尤度もしたいけど、関数はあるか？

```

## ブートストラップ
```{r}

res_boot <- boo_sam(res_sam, n=100,method="p",seed=1)

## 親魚量のブートストラップ信頼区間のプロット
years <- colnames(dat$caa)
ssb_boot <- sapply(res_boot,function(x) colSums(x$ssb))
x <- t(apply(ssb.boot,1,quantile,probs=c(0.1,0.5,0.9)))
matplot(Years,x,ylim=c(0,max(x)),col=1,type=c("l","b","l"),
        pch=1,lty=c(2,1,2),ylab="Spawning biomass")
```

## cross test

```{r}
pdata <- popsim_vpasam(res_sam, n=100)
res_vpa_list <- list()
for(i in 1:length(pdata)){
  vpainput <- res_vpa$input
  vpainput$dat <- pdata[[i]]
  res_vpa_list[[i]] <- do.call(vpa, vpainput)
}

res_vpa_list[[1]] <- res_sam

# 1番目がSAMの結果  (なんか関数ある？)
plot_vpa(res_vpa_list, legend.position="none", what.plot=c("SSB", "biomass", "U", "Recruitment"))
```

## 将来予測

