cat("R version: ", R.version.string, "\n", sep = "")
print(.libPaths())
library(frasam)
cat("frasam path: ", find.package("frasam"), "\n", sep = "")
print(utils::data(package = "frasam")$results[, c("Item", "Title"), drop = FALSE])
setwd(tempdir())
data(res_bh)
stopifnot(inherits(res_bh, "sam"))
cat("data(res_bh): OK\n")
